<?php

namespace App\Models;

use App\Traits\ClearValidated;
use App\Traits\CreatedAtOrdered;
use App\Traits\RusMonth;
use App\Traits\UseImages;
use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Cache;

class Article extends Model
{
    use UseImages;
    use RusMonth;
    use ClearValidated;
    use CreatedAtOrdered;

    protected $fillable = [
        'title',
        'notice',
        'content',
        'slug',
        'user_id'
    ];

    protected $with = [
        'image',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function(self $article) {
            Cache::forget('sitemap.2g');
        });
        self::updating(function(self $article) {
            Cache::forget('sitemap.2g');
        });
        self::deleting(function(self $article) {
            Cache::forget('sitemap.2g');
        });
    }
}
