<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Cache;

class Metro extends Model
{
  public const COLORS = [
    'green' => 'Зелёный',
    'red' => 'Красный',
    'yellow' => 'Жёлтый',
    'blue' => 'Синий',
    'light-blue' => 'Голубой',
    'brown' => 'Коричневый',
    'orange' => 'Оранжевая',
    'purple' => 'Фиолетовая',
    'grey' => 'Серая',
    'lime' => 'Салатовая',
    'teal' => 'Бирюзовая',
    'blue-gray' => 'Серо-голубая',
  ];

  public const ARRAY_COLORS = [
    'green',
    'red',
    'yellow',
    'blue',
    'light-blue',
    'brown',
    'orange',
    'purple',
    'grey',
    'lime',
    'teal',
    'blue-gray'
  ];

  public const COLORS_HEX = [
    'green' => '00FF00',
    'red' => 'FF0000',
    'yellow' => 'FFFF00',
    'blue' => '0000FF',
    'light-blue' => '80A6FF',
    'brown' => '964b00',
    'orange' => 'ffa500',
    'purple' => '8b00ff',
    'grey' => '808080',
    'lime' => '7fff00',
    'teal' => '30d5c8',
    'blue-gray' => '77a1b5'
  ];

  protected $fillable = [
    'color',
    'name',
    'distance',
    'hotel_id',
  ];

  protected static function boot()
  {
    parent::boot(); // TODO: Change the autogenerated stub
    self::creating(function (self $metro) {
      Cache::forget('sitemap.2g');
    });
    self::updating(function (self $metro) {
      Cache::forget('sitemap.2g');
    });
    self::deleting(function (self $metro) {
      Cache::forget('sitemap.2g');
    });
  }

  public function hotel(): BelongsTo
  {
    return $this->belongsTo(Hotel::class);
  }
}
