<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Cache;

class Metro extends Model
{
    const COLORS = [
        'green' => 'Зелёный',
        'red' => 'Красный',
        'yellow' => 'Жёлтый',
        'blue' => 'Синий',
        'light-blue' => 'Голубой',
        'brown' => 'Коричневый',
        'orange' => 'Оранжевая',
        'purple' => 'Фиолетовая',
        'grey' => 'Серая',
        'lime' => 'Салатовая',
        'teal' => 'Бирюзовая',
        'blue-gray' => 'Серо-голубая',
    ];

    protected $fillable = [
        'color',
        'name',
        'distance',
        'hotel_id',
    ];

    public function hotel(): BelongsTo
    {
        return $this->belongsTo(Hotel::class);
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function(self $metro) {
            Cache::forget('sitemap.2g');
        });
        self::updating(function(self $metro) {
            Cache::forget('sitemap.2g');
        });
        self::deleting(function(self $metro) {
            Cache::forget('sitemap.2g');
        });
    }
}
