<?php

namespace App\Models;

use App\Traits\CreatedAtOrdered;
use App\Traits\UseImages;
use App\User;
use Eloquent;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Query\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Cache;

/**
 * App\Models\Page
 *
 * @property int                     $id
 * @property string                  $title
 * @property string                  $slug
 * @property string                  $content
 * @property int|null                $user_id
 * @property Carbon|null             $deleted_at
 * @property Carbon|null             $created_at
 * @property Carbon|null             $updated_at
 * @property string|null             $header
 * @property string|null             $footer
 * @property-read mixed              $meta_description
 * @property-read mixed              $meta_keywords
 * @property-read mixed              $meta_title
 * @property-read Image              $image
 * @property-read Collection|Image[] $images
 * @property-read int|null           $images_count
 * @property-read PageDescription    $meta
 * @property-read User|null          $user
 *
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Eloquent\Builder|Page newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Page newQuery()
 * @method static Builder|Page onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|Page query()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereFooter($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereHeader($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Page whereUserId($value)
 * @method static Builder|Page withTrashed()
 * @method static Builder|Page withoutTrashed()
 * @mixin Eloquent
 */
class Page extends Model
{
    use SoftDeletes;
    use UseImages;
    use CreatedAtOrdered;

    protected $fillable = [
        'title',
        'slug',
        'content',
        'header',
        'footer',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function (self $page) {
            Cache::forget('sitemap.2g');
        });
        self::updating(function (self $page) {
            Cache::forget('sitemap.2g');
        });
        self::deleting(function (self $page) {
            Cache::forget('sitemap.2g');
        });
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function attachMeta(Request $request): Page
    {
        if (! $request->get('meta_title', false) && ! $request->get('meta_description', false) && ! $request->get('meta_keywords', false)) {
            return $this;
        }

        $key = $this->getRouteKeyName();
        $url = '/'.$this->$key;

        $data = [];
        $data['title'] = $request->get('meta_title');
        $data['meta_description'] = $request->get('meta_description');
        $data['meta_keywords'] = $request->get('meta_keywords');
        $data['url'] = $url;
        $data['model_type'] = self::class;

        $meta = PageDescription::updateOrCreate(['url' => $url], $data);
        $meta->model_type = self::class;
        $meta->save();

        $this->meta()->save($meta);

        return $this;
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    public function meta(): HasOne
    {
        return $this
          ->hasOne(PageDescription::class, 'model_id')
          ->where('model_type', self::class);
    }

    public function getMetaDescriptionAttribute(): ?string
    {
        return @$this->meta->meta_description ?? null;
    }

    public function getMetaKeywordsAttribute(): ?string
    {
        return @$this->meta->meta_keywords ?? null;
    }

    public function getMetaTitleAttribute(): ?string
    {
        return @$this->meta->title ?? null;
    }
}
