<?php

namespace App\Models;

use App\Traits\CreatedAtOrdered;
use App\Traits\UseImages;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class PageDescription extends Model
{
    use UseImages;
    use CreatedAtOrdered;

    protected $fillable = [
        'url', 'title', 'meta_description', 'meta_keywords', 'description'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function(self $pageDescription) {
            Cache::forget('sitemap.2g');
        });
        self::updating(function(self $pageDescription) {
            Cache::forget('sitemap.2g');
        });
        self::deleting(function(self $pageDescription) {
            Cache::forget('sitemap.2g');
        });
    }
}
