<?php

namespace App\Models;

use Eloquent;
use App\Traits\UseImages;
use Illuminate\Support\Carbon;
use App\Traits\CreatedAtOrdered;
use Illuminate\Support\Facades\Cache;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;

/**
 * App\Models\PageDescription
 *
 * @property int                     $id
 * @property string                  $url
 * @property string|null             $title
 * @property string|null             $meta_description
 * @property string|null             $meta_keywords
 * @property string|null             $description
 * @property Carbon|null             $created_at
 * @property Carbon|null             $updated_at
 * @property string|null             $model_type
 * @property int|null                $model_id
 * @property-read Image              $image
 * @property-read Collection|Image[] $images
 * @property-read int|null           $images_count
 * @property string|null             $h1
 * @method static Builder|PageDescription newModelQuery()
 * @method static Builder|PageDescription newQuery()
 * @method static Builder|PageDescription query()
 * @method static Builder|PageDescription whereCreatedAt($value)
 * @method static Builder|PageDescription whereDescription($value)
 * @method static Builder|PageDescription whereId($value)
 * @method static Builder|PageDescription whereMetaDescription($value)
 * @method static Builder|PageDescription whereMetaKeywords($value)
 * @method static Builder|PageDescription whereModelId($value)
 * @method static Builder|PageDescription whereModelType($value)
 * @method static Builder|PageDescription whereTitle($value)
 * @method static Builder|PageDescription whereUpdatedAt($value)
 * @method static Builder|PageDescription whereUrl($value)
 * @mixin Eloquent
 */
class PageDescription extends Model
{
  use UseImages;
  use CreatedAtOrdered;

  protected $fillable = [
    'url', 'title', 'meta_description', 'meta_keywords', 'description', 'h1'
  ];

  protected static function boot()
  {
    parent::boot(); // TODO: Change the autogenerated stub
    self::creating(function (self $pageDescription) {
      Cache::forget('sitemap.2g');
    });
    self::updating(function (self $pageDescription) {
      Cache::forget('sitemap.2g');
    });
    self::deleting(function (self $pageDescription) {
      Cache::forget('sitemap.2g');
    });
  }
}
