<?php

namespace App\Models;

use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Cache;

/**
 * App\Models\Rating
 *
 * @property int                 $id
 * @property int                 $value
 * @property int                 $category_id
 * @property int                 $review_id
 * @property Carbon|null         $created_at
 * @property Carbon|null         $updated_at
 * @property-read RatingCategory $category
 * @property-read Review         $review
 *
 * @method static Builder|Rating newModelQuery()
 * @method static Builder|Rating newQuery()
 * @method static Builder|Rating query()
 * @method static Builder|Rating whereCategoryId($value)
 * @method static Builder|Rating whereCreatedAt($value)
 * @method static Builder|Rating whereId($value)
 * @method static Builder|Rating whereReviewId($value)
 * @method static Builder|Rating whereUpdatedAt($value)
 * @method static Builder|Rating whereValue($value)
 * @mixin Eloquent
 */
class Rating extends Model
{
    protected $fillable = [
        'category_id',
        'value',
    ];

    protected $with = [
        'review',
        'category',
    ];

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(static function (self $rating) {
            Cache::forget('sitemap.2g');
        });
        self::updating(static function (self $rating) {
            Cache::forget('sitemap.2g');
        });
        self::deleting(static function (self $rating) {
            Cache::forget('sitemap.2g');
        });
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(RatingCategory::class);
    }

    public function review(): BelongsTo
    {
        return $this->belongsTo(Review::class);
    }
}
