name: Check-errors-dev

#on: 
#  push:
#    branches: 
#      - develop

jobs:
  laravel:
    runs-on: ubuntu-latest
    container: 
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gorooms
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3    

      redis:
        image: redis
        ports:
          - 6379/tcp
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
    - name: checkout repo
      uses : actions/checkout@v3
    
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16     
    
    - name: Install additional PHP extensions
      run : |
        apt install -y php8.1 php8.1-bz2 php8.1-zip php8.1-readline php8.1-mysql php8.1-mbstring php8.1-gd php8.1-curl php-php-gettext php-json php-gd
        apt install -y composer curl 

    - name: Install node
      run : |
        apt install -y npm
   
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Install Composer dependencies
      run: composer install

    - name: Prepare the application
      run : |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        php artisan migrate --force
        php artisan storage:link
        npm run prod
        make check
        make test  
  
# #  Deploy:
#     runs-on: ubuntu-latest
#     needs: [laravel-tests]

#     steps:
#     - name: Install Composer dependencies
#       run: composer install

#     - name: Prepare the application
#       run : |
#         php -r "file_exists('.env') || copy('.env.example', '.env');"
# #        php artisan down
#         php artisan migrate --force
#         php artisan storage:link
#         npm run prod
# #        php artisan up
#         make check
#         make test
