name: check and deploy

on: 
#  push:
  workflow_dispatch
#    branches: 
#      - develop

jobs:
  build:
    runs-on: ubuntu-latest
#    container: 
#      image: kirschbaumdevelopment/laravel-test-runner:8.1
# image not have services and sudo
    env:
      ROOT_PASSWORD: root
      ROOT_USER: root
      MYSQL_DB: gorooms
      
    # in service use env variable for current service. for mysql - MYSQL_ROOT_PASSWORD
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DB }}

        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

      redis:
        image: redis
        ports:
          - 6379/tcp
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
        
    - name: Set up MySQL
      run: |
        sudo apt install net-tools
        sudo systemctl start mysql
        sudo netstat -ntulp
        sudo mysql -e 'show grants;' -u${{ env.ROOT_USER }} -p${{ env.ROOT_PASSWORD }} --host 127.0.0.1
        sudo mysql -e 'show databases;' -u${{ env.ROOT_USER }} -p${{ env.ROOT_PASSWORD }} --host 127.0.0.1
        mysql -e 'CREATE DATABASE ${{ env.MYSQL_DB }};' -u${{ env.ROOT_USER }} -p${{ env.ROOT_PASSWORD }} --host 127.0.0.1
#        sudo systemctl start redis-server

    - name: checkout repo
      uses : actions/checkout@v3 
    
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'     
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: dom, curl, mbstring, libxml, zip, gd, json, mysql, readline, bz2    
   
    - name: Install Composer dependencies
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        sudo apt install -y composer
        composer install
        
    - name: Install node
      run : |
        sudo apt install -y nodejs
        curl -L https://npmjs.org/install.sh | sudo sh
        npm install

    - name: Check application
      run : |
        php artisan migrate --force
        php artisan storage:link
        npm run build
        make check
        make test
        
              
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd ${{ secrets.PATHGOROOMS }} && ./.scripts/check.sh"

