name: selfcheck and deploy

on:
#  push:
  workflow_dispatch
#    branches:
#      - develop

jobs:
  build:
    runs-on: self-hosted

    env:
      ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWD }}
      ROOT_USER: root
      MYSQL_DB: gorooms_devDB
      MYSQL_DB_TEST: gorooms_test

    steps:

    - name: checkout repo
      uses : actions/checkout@v3

    - name: Install Composer dependencies
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        sed -i "12s/^DB_DATABASE=root/DB_DATABASE=${{ env.MYSQL_DB_TEST }}/" .env
        sed -i "14s/^DB_PASSWORD=root/DB_PASSWORD=${{ env.ROOT_PASSWORD }}/" .env
        php -r "file_exists('.env.testing') || copy('env_tests', '.env.testing');"
        sed -i "10s/^DB_DATABASE=root/DB_DATABASE=${{ env.MYSQL_DB_TEST }}/" .env.testing
        sed -i "12s/^DB_PASSWORD=root/DB_PASSWORD=${{ env.ROOT_PASSWORD }}/" .env.testing
        composer install
        npm install
        mysql -e 'show tables in gorooms_test;' -u${{ env.ROOT_USER }} -p${{ env.ROOT_PASSWORD }} --host 127.0.0.1

    - name: Check application
      run : |
        cat .env.testing
        php artisan migrate --force
        php artisan storage:link
        npm run build
        make check
        make test


  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd ${{ secrets.PATHGOROOMS }} && ./.scripts/check.sh"
